// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPrioridades.DAL;

#nullable disable

namespace RegistroPrioridades.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("RegistroPrioridades.Models.Cliente", b =>
            {
                b.Property<int>("ClienteId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Celular")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Direccion")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nombres")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("RNC")
                    .IsRequired()
                    .HasMaxLength(9)
                    .HasColumnType("TEXT");

                b.Property<string>("Telefono")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("ClienteId");

                b.ToTable("Clientes");
            });

            modelBuilder.Entity("RegistroPrioridades.Models.Prioridad", b =>
            {
                b.Property<int>("PrioridadId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("DiasCompromiso")
                    .IsRequired()
                    .HasColumnType("INTEGER");

                b.HasKey("PrioridadId");

                b.ToTable("Prioridades");
            });

            modelBuilder.Entity("RegistroPrioridades.Models.Sistema", b =>
            {
                b.Property<int>("SistemaId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Nombre")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("SistemaId");

                b.ToTable("Sistemas");
            });

            modelBuilder.Entity("RegistroPrioridades.Models.Ticket", b =>
            {
                b.Property<int>("TicketId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Asunto")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("ClienteId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Fecha")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("PrioridadId")
                    .HasColumnType("INTEGER");

                b.Property<int>("SistemaId")
                    .HasColumnType("INTEGER");

                b.Property<string>("SolicitadoPor")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("TicketId");

                b.ToTable("Tickets");
            });
#pragma warning restore 612, 618
        }
    }
}
